import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ChatInterface from '@/Chat'
import {useMSGStore} from "@/Chat/store/messages"
import {useActorsStore} from '@/Chat/store/actors'
import {useEffect} from "react"

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [setMessage, updateMessage] = useMSGStore((s) => [s.setMessage, s.updateMessage])
  const [setActors] = useActorsStore((s) => [s.setActors])

  useEffect(() => {
    setActors({
      "Bot" : {
        name: "Bot",
        type: "Bot",
        image: "https://res.cloudinary.com/duvaex4uc/image/upload/v1688500304/janraqbmycariuow6jus.webp"
      },
      "James" : {
        name: "James",
        type: "User",
        image: "https://res.cloudinary.com/duvaex4uc/image/upload/v1683490676/hwepwcxy7vxp7y6gltrp.webp"
      },
    })
  }, [])


  function addRandomMessage() {
    let random = Math.random() < 0.5;
    let test1 = (Math.random() + 1).toString(36).substring(7);
    let test2 = (Math.random() + 1).toString(36).substring(7);

    setMessage({
      actor: random ? "James" : "Bot",
      contents: [
        {
          contentType: "text",
          content: test1,
        },
        {
          contentType: "text",
          content: test2,
        }
      ]
    })
  }

  function addDelayedMessage() {
    let random = Math.random() < 0.5;
    let test = (Math.random() + 1).toString(36).substring(7);

    let index = setMessage({
      actor: random ? "James" : "Bot",
      loading: true,
      contents: [
        {
          contentType: "text",
          content: test,
        }
      ]
    })

    function showTime() {
      let dateTime= new Date();
      let time = dateTime.toLocaleTimeString();

      updateMessage(index, {
        actor: random ? "James" : "Bot",
        loading: false,
        contents: [
          {
            contentType: "text",
            content: time,
          }
        ]
      })
    }

    setInterval(showTime, 2000);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.description}>
          <ChatInterface/>
        </div>
        <div className={styles.grid}>
            <button onClick={()=>addRandomMessage()}>Add Message</button>
            <button onClick={()=>addDelayedMessage()}>Delayed Message</button>
        </div>
      </main>
    </>
  )
}
